### ISSUE TITLE
Error: window is not defined

### ISSUE THREAD

**Issue by git-no** [GrayFrost/sveaflet#10]
First: thank you, very interesting repository and module.

Following your _quick start_ description I got the error`windows is not defined`.

From my point of view the reason seems some components do not support server side or static side rendering and the 
error happens on import the Map (maybe also other) component. 
Leaflet needs a browser window, has client rendering.

The svelte solution could be to load Leaflet libarary (L) on Svelte onMount.

Are you considering to support SvelteKit SSR in the near future?

Thanks for your response. Regards

**Comment by GrayFrost** [comment]
> First: thank you, very interesting repository and module.
> 
> Following your _quick start_ description I got the error`windows is not defined`.
> 
> From my point of view the reason seems some components do not support server side or static side rendering and the error happens on import the Map (maybe also other) component. Leaflet needs a browser window, has client rendering.
> 
> The svelte solution could be to load Leaflet libarary (L) on Svelte onMount.
> 
> Are you considering to support SvelteKit SSR in the near future?
> 
> Thanks for your response. Regards

I think you can write `export const ssr = false;` in your +page.js, here's the [guide](https://kit.svelte.dev/docs/page-options#ssr)

**Comment by GrayFrost** [comment]
> @GrayFrost Thank you for the response.
> 
> 
> 
> I am aware of the option `export const ssr = false;` but this is an option often in projects does not fit requirements, e.g. dynamic pages like `src/routes/blog/[slug]`.
> 
> 
> 
> The solution could be to dynamic import Leaflet L and use Svelte onMount to configure L.
> 
> 

yeah,it's another choice. This is common feature that most ssr frameworks have. Useful solution is to load library in mount hooks or set ssr to false.For example: In Nextjs, you can dynamic import library and set option ssr to fase.
