### ISSUE TITLE
Marker position isn't bound in Svelte 5

### ISSUE THREAD

**Issue by bddvlpr** [GrayFrost/sveaflet#17]
I'm halfway through porting my project from `sveltejs-leaflet` to `sveaflet` but I just figured out the markers aren't reacting to any state changes in Svelte 5. Unsure if this is happening in Svelte 4.

In the example below, the popup text is correctly changed on state change but the position is always the same. In `sveltejs-leaflet` this would cause the marker to update, is there an alternative for this in `sveaflet`? This can be solved by wrapping it in a `{#key}` but this would also cause the pop up to close as the entire component is being re-created.
```svelte
<script lang="ts">
	import { Map, TileLayer, Marker, Popup } from 'sveaflet';

	let position = $state([51.505, -0.09]);

	$effect(() => {
		setInterval(() => {
			position = [position[0] + 0.01, position[1] + 0.02];
		}, 1000);
	});
</script>

<div style="width:100%;height:500px;">
	<Map
		options={{
			center: [51.505, -0.09],
			zoom: 13
		}}
	>
		<TileLayer url={'https://tile.openstreetmap.org/{z}/{x}/{y}.png'} />
		<Marker latLng={position}>
			<Popup>
				{position}
			</Popup>
		</Marker>
	</Map>
</div>
```

Great job on the library so far, way better option in my opinion.

**Comment by GrayFrost** [comment]
> I'm halfway through porting my project from `sveltejs-leaflet` to `sveaflet` but I just figured out the markers aren't reacting to any state changes in Svelte 5. Unsure if this is happening in Svelte 4.
> 
> In the example below, the popup text is correctly changed on state change but the position is always the same. In `sveltejs-leaflet` this would cause the marker to update, is there an alternative for this in `sveaflet`? This can be solved by wrapping it in a `{#key}` but this would also cause the pop up to close as the entire component is being re-created.
> 
> ```svelte
> <script lang="ts">
> 	import { Map, TileLayer, Marker, Popup } from 'sveaflet';
> 
> 	let position = $state([51.505, -0.09]);
> 
> 	$effect(() => {
> 		setInterval(() => {
> 			position = [position[0] + 0.01, position[1] + 0.02];
> 		}, 1000);
> 	});
> </script>
> 
> <div style="width:100%;height:500px;">
> 	<Map
> 		options={{
> 			center: [51.505, -0.09],
> 			zoom: 13
> 		}}
> 	>
> 		<TileLayer url={'https://tile.openstreetmap.org/{z}/{x}/{y}.png'} />
> 		<Marker latLng={position}>
> 			<Popup>
> 				{position}
> 			</Popup>
> 		</Marker>
> 	</Map>
> </div>
> ```
> 
> Great job on the library so far, way better option in my opinion.

Got it! I will check whether it's a problem this weekend.

**Comment by GrayFrost** [comment]
> I'm halfway through porting my project from `sveltejs-leaflet` to `sveaflet` but I just figured out the markers aren't reacting to any state changes in Svelte 5. Unsure if this is happening in Svelte 4.
> 
> In the example below, the popup text is correctly changed on state change but the position is always the same. In `sveltejs-leaflet` this would cause the marker to update, is there an alternative for this in `sveaflet`? This can be solved by wrapping it in a `{#key}` but this would also cause the pop up to close as the entire component is being re-created.
> 
> ```svelte
> <script lang="ts">
> 	import { Map, TileLayer, Marker, Popup } from 'sveaflet';
> 
> 	let position = $state([51.505, -0.09]);
> 
> 	$effect(() => {
> 		setInterval(() => {
> 			position = [position[0] + 0.01, position[1] + 0.02];
> 		}, 1000);
> 	});
> </script>
> 
> <div style="width:100%;height:500px;">
> 	<Map
> 		options={{
> 			center: [51.505, -0.09],
> 			zoom: 13
> 		}}
> 	>
> 		<TileLayer url={'https://tile.openstreetmap.org/{z}/{x}/{y}.png'} />
> 		<Marker latLng={position}>
> 			<Popup>
> 				{position}
> 			</Popup>
> 		</Marker>
> 	</Map>
> </div>
> ```
> 
> Great job on the library so far, way better option in my opinion.

Hi, bddvlpr! I have tested the situation. Because Sveaflet right now is written by Svelte 4, when you use it in Svelte 5 environment, the array state you declare turns into a proxy object, I think this is a break changes. Maybe I  will support a newly Svelte5 version when Svelte 5 is stable, or you can try [$state.snapshot](https://svelte-5-preview.vercel.app/docs/runes#$state-snapshot)
<img width="1241" alt="image" src="https://github.com/user-attachments/assets/b57dac4c-a9f1-4365-b805-092711e4f6b3">

**Comment by GrayFrost** [comment]
> workaround

So far `updateProps` not support proxy value's comparison, yeah, if support svelte5 later, i will optimize this function.
Thanks for your support.

**Comment by GrayFrost** [comment]
> Is this what the `updateProps` util provides? I've found a workaround in Svelte 5 that I'm trying to apply to your library. I'll keep you posted.

So far `updateProps` not support proxy value's comparison, yeah, if support svelte5 later, i will optimize this function.
Thanks for your support.
